### ISSUE TITLE
Feature: Blank Node Management

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#105]
Blank nodes are no stable references in RDF, see https://www.w3.org/TR/rdf11-concepts/#section-blank-nodes

rdf4cpp is not trying to prevent blank node ID collisions. Scopes allow the the user to correctly use blank nodes within files and graph stores/datasets. Comparison between blank nodes from different scopes is technically possible within rdf4cpp but not allowed by RDF. 

- [ ] By default, we should not keep the identifier of a blank node loaded from file but assign new ones
- [ ] There should be a generator that you can ask for a fresh, so far unused identifier
  - [ ] replacable
  - Variants:
    - [ ] Random IDs (could be UUIDs)
    - [ ] increasing IDs
      - [ ] should be as short as allowed in turtle
      - [ ] optional user-defined pre- or suffix
- [ ] There should be a BlankNodeMapper that keeps track of what blank node identifiers from a file are represented by what blank node identifiers in a NodeStorage. (Scopes)
  - [ ] This needs exemplary use-cases to get an idea for a good interface.
  - [x] Check how other libraries handle that
  - [ ] Needs to be separated into front and backend. Backend without virtual methods (see tentris)
  - [ ] Should be able to support both RDF Dataset semantics merge and union (see https://www.w3.org/TR/rdf11-datasets/#default-graph-as-union-or-as-merge)
- [ ] There should be subscopes. Subscopes know all blank nodes from their parent scope. 
  - [ ] Subscopes are initialized with all blank nodes from their parent scope. If a blank node is added to a parent scope, it is forwarded to the subscope.
- [ ] A scope is not bound to a NodeStorage. Each method has a node_storage argument with a default value
- [ ] Add support for [Skolem IRIs](https://www.w3.org/TR/rdf11-concepts/#section-blank-nodes)

*Note:* SPARQL variables are not handled as blank nodes but as anonymous variables. Thus, name clashes between variables and blank nodes are no concern.

**Comment by liss-h** [comment]
Jena:
- [Node ids are random UUIDS](https://github.com/apache/jena/blob/main/jena-core/src/main/java/org/apache/jena/graph/BlankNodeId.java#L72)
- [saves result in a `String -> Node` map to retrieve later](https://github.com/apache/jena/blob/main/jena-arq/src/main/java/org/apache/jena/riot/lang/BlankNodeAllocatorGlobal.java#L44)
- [connection point of links above](https://github.com/apache/jena/blob/main/jena-core/src/main/java/org/apache/jena/graph/NodeFactory.java#L41)
