### ISSUE TITLE
Comparison of literals with language tags

### ISSUE THREAD

**Issue by nkaralis** [TortugaAttack/rdf4cpp#117]
Currently, the expression `"DEF"@en-US == "DEF"@en-us` (consider them being literals) evaluates to false. 
[RFC 4646](https://www.ietf.org/rfc/rfc4646) states in section 2.1 (page 5):

_The tags and their subtags, including private use and extensions, are to be treated as case insensitive: there exist conventions for the capitalization of some of the subtags, but these MUST NOT be taken to carry meaning._

I believe that the above expression should evaluate to true. 
This is also the case in following test case:

- https://github.com/w3c/rdf-tests/blob/main/sparql11/data-sparql11/functions/strlang03.rq (query)
- https://github.com/w3c/rdf-tests/blob/main/sparql11/data-sparql11/functions/strlang03-rdf11.srx (results)

Note that the query uses "en-US", whereas in the results "en-us" is used.

**Comment by liss-h** [comment]
#122
