### ISSUE TITLE
Precision error when adding doubles and decimals

### ISSUE THREAD

**Issue by nkaralis** [TortugaAttack/rdf4cpp#119]
Reference test case:

- https://github.com/w3c/rdf-tests/blob/main/sparql11/data-sparql11/aggregates/agg-sum-02.rq (query)
- https://github.com/w3c/rdf-tests/blob/main/sparql11/data-sparql11/aggregates/agg-numeric2.ttl (data)

Expected results for `:mixed2`: 4E-1; actual result: 4.0000000298023225E-1

**Comment by liss-h** [comment]
fix merged, closing
