### ISSUE TITLE
Casting operations

### ISSUE THREAD

**Issue by nkaralis** [TortugaAttack/rdf4cpp#120]
There are some issues with casting operations

- Casting to boolean currently relies on EBV. This is not always desired. For example, when casting strings to boolean, the rules for casting from string need to be followed (see: https://www.w3.org/TR/xpath-functions/#casting-from-strings)
-  Currently, when casting to string, the code only pays attention to the lexical form. When casting numerical datatypes, and especially decimals, doubles and floats, to string the spec provides a set of rules that need to be followed (see: https://www.w3.org/TR/xpath-functions/#casting-to-string).

**Comment by liss-h** [comment]
#122
