### ISSUE TITLE
Literal::lang_matches behaviour

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#142]
Currently there is `Literal::lang_matches(std::string_view lang_range)` which checks if the language tag of the given literal matches `lang_range`. I.e. the following C++ code:

```c++
auto lit = Literal::make_lang_tagged("Liss", "en");
return lit.lang_matches("en");
```
Is equivalent to this SPARQL code (notice the additional inserted `lang()` call)
```sparql
langMatches(lang("Liss"@en) , "en")
```

<br>----------------------------------

If `Literal::lang_matches` were to behave like the standard wants it should be more like the following:
```c++
auto lit = Literal::make_simple("en");
return lit.lang_matches("en");
```

To get the old behaviour back you would then need to write (after another function: `Literal::as_language_tag` is added):
```c++
auto lit = Literal::make_lang_tagged("Liss", "en");
return lit.as_language_tag().lang_matches("en");
```

<br>----------------------------------

Solutions:
Personally I prefer the current behaviour so I would keep it as well, only problem is naming:

Best I could come up with, still ugly:
```c++
struct Literal {
    /**
     * returns true if this->language_tag() matches lang_range
     */
    util::TriBool language_tag_matches_range(std::string_view lang_range) const noexcept;
    Literal as_language_tag_matches_range(std::string_view lang_range, NodeStorage &) const noexcept;
    Literal as_language_tag_matches_range(Literal const &lang_range, NodeStorage &) const noexcept; // lang_range is xsd:string

    /**
     * returns true if this->language_tag() == other.language_tag()
     * (also rename Literal::datatype_matches to Literal::datatype_eq)
     */
    util::TriBool language_tag_eq(Literal const &other) const noexcept;

    /**
     * effectively returns Literal::make_simple(this->language_tag());
     * for good measure because as_lexical_form() also exists 
     * (and can be implemented more efficiently if we have lang tag inlining in the future)
     */
    Literal as_language_tag(NodeStorage &) const noexcept;
};

util::TriBool lang_matches(std::string_view lang_tag, std::string_view lang_range);
Literal lang_matches(Literal const &lang_tag, Literal const &lang_range); // needs 2 xsd:strings
```

**Comment by bigerl** [comment]
Not much to add here. Good point. I would say, first, it is important to fully support the relevant parts directly, such that one SPARQL function call = one C++ function call. Optimized short cuts are fine but no replacement.
