### ISSUE TITLE
Bug: xsd:decimal has invalid internal representation

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#172]
Currently `xsd:decimal` is internally represented as `boost::multiprecision::dec_float` (a decimal arbitrary precision decimal **floating** point value).

This is invalid because it results in precision errors in math operations. Consider the following code:
```c++
auto sum = 1_xsd_int + 2_xsd_int + 3_xsd_int;
auto avg = sum / 3_xsd_int;

CHECK(avg == "2.0"_xsd_decimal); // fails with expansion: 2.0 == 2.0
```

The fix is to implement `xsd:decimal`'s internal represenstation like java's `BigDecimal`, i.e. an arbitrary precision integer unscaled value (`boost::multiprecision::cpp_int`) with a `uint32_t` scale. Such that `value = unscaled_value * 10^(-scale)`.

This is also what the spec implies: https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#dt-decimal.

For some information on the implementation details (e.g. how to choose the scale) the java `BigDecimal` docs should be helpful: https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html.

**Comment by bigerl** [comment]
Alternative is, of course, to find a type that implements it already. Problem would probably be the compatibility with other boost types.
