### ISSUE TITLE
Slow serilization of string literals

### ISSUE THREAD

**Issue by nkaralis** [TortugaAttack/rdf4cpp#190]
Currently, the serialization of string literals is slow.
Possible cause: the escaping process.

**Comment by liss-h** [comment]
Hopefully fixed by #191, needs further testing

**Comment by liss-h** [comment]
Should be further improved by #218

**Comment by liss-h** [comment]
One still existing problem is that accessing the literal lexical form and language tag may cause a heap allocation for some types. An interface to write it directly to a buffer is missing

**Comment by liss-h** [comment]
Closed by #191 #218 #239
