### ISSUE TITLE
Parser crash

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#211]
This triple crashes the parser:
```
<http://dbpedia.org/resource/Nikolai_Skoblin> <http://dbpedia.org/ontology/deathDate> "1937-0-0"^^<http://www.w3.org/2001/XMLSchema#date> .
```

used:
```c++
{
    using namespace rdf4cpp::rdf;
    parser::ParsingFlags flags = parser::ParsingFlag::Turtle;
    for (const auto &e: parser::RDFFileParser{filename, flags}) {
      if (e.has_value()) {
        count++;
      } else
        std::cerr << e.error();
    }
  }
```

**Comment by KonradHoeffner** [comment]
I think that may actually be a fault in the triple, where the month and date are missing the second digit.
At least according to <https://www.w3schools.com/xml/schema_dtypes_date.asp>, the date should be YYYY-MM-DD.
However I don't know if rdf4cpp actually parses this as a timestamp or if it is saved as a string value instead.
I will temporarily add the missing leading zeroes and try if that fixes the error.

**Comment by KonradHoeffner** [comment]
No, adding the leading zeroes doesn't help, it seems to crash when the day or month are either "0" or "00".

**Comment by liss-h** [comment]
Should be fixed on develop now
