### ISSUE TITLE
Feature: DBpedia mode for literal parsing

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#214]
DBpedia is important to support but it's literals are messy. 

How to handle it: a DBpedia mode
- [ ] extract all literals from DBpedia (plain text, not normalized or anything)
- [ ] add an relaxed-parsing flag, let's call it `dbpediamode`, that accepts all the wrong things in DBpedia's literals and makes them right.

**Comment by liss-h** [comment]
Suggestion: mode to put faulty literals into the fallback literal backend
