### ISSUE TITLE
Node constructor validation

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#261]
`BlankNode`, `Variable` and `IRI` constructors should validate the passed in values.

Additionally, add `BlankNode::make_unchecked` and friends to be able to construct nodes without these checks (probably still add asserts in those tho).

**Comment by liss-h** [comment]
Would be nice if this could be done with SIMD

**Comment by bigerl** [comment]
If you do SIMD, please check out available libraries that automatically support fallback to non-SIMD code if the compiler or target does not support it.
