### ISSUE TITLE
Jena complains about characters in rdf4cpp tri-g/ttl output

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#307]
**Describe the bug**
I loaded [this dbpedia file](https://files.dice-research.org/projects/debug_rdf4cpp/dbpedia-2022-12.ttl.zst) and dumped it [into this](https://files.dice-research.org/projects/debug_rdf4cpp/dbpedia-2022-12_dedup.ttl.zstd). 

Parsing it again with [jena 5.1.0](https://dlcdn.apache.org/jena/binaries/apache-jena-5.1.0.zip)'s `turtle` command shows warnings that we are using illegal characters. I've attached the logfile

[parsing_rdf4cpp_output_with_riot.log.zip](https://github.com/user-attachments/files/17071911/parsing_rdf4cpp_output_with_riot.log.zip)

```
zstdcat dbpedia-2022-12.ttl.zst | turtle --output=TURTLE > /dev/null 2> parsing_rdf4cpp_output_with_riot.log
```

**Comment by liss-h** [comment]
Is a bug in jena, nothing to fix. https://github.com/apache/jena/issues/2766
