### ISSUE TITLE
Non-Canonical Literals

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#44]
## Issue:
If `?x = "2.0"^^xsd:double` and `?y="2.00"^^xsd:double` the following filter should remove the binding:

```
filter(str(?x) = str(?y))
```

This will not happen when the bindings for ?x and ?y are canonized to `"2.0"^^xsd:double`.

## Open questions:
- When is it allowed in triple stores to drop non-canonical literals in favor of the canonical form?

**Comment by liss-h** [comment]
Literals are being canonicalized already if the datatype is registered
