### ISSUE TITLE
Undefined behaviour in various from_string functions

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#46]
The from_string implementations of 

- Decimal
- Integer 
- String 
- Float

rely on std::string_view being null-terminated by using the .data() member in combination with functions expecting null-terminated strings. std::string_view does not guarantee being null-terminated; this results in a buffer-overread if it is not.

broken code example: https://godbolt.org/z/qsjKehjh7

To fix:
- use std::from_chars instead of std::strtod, std::stof, std::strtol as it accepts and end pointer
- use std::string_view constructor of std::string instead of the char const * constructor
- for std::regex_match there is no easy fix except converting to std::string

**Comment by bigerl** [comment]
oops. I completely overlooked that when reviewing the PRs. 

Both approaches sound fine. I would prefer the from_chars function where possible. 

Could you patch it and make a PR?

**Comment by liss-h** [comment]
fixed: https://github.com/rdf4cpp/rdf4cpp/pull/49
