### ISSUE TITLE
Literal operator== doesn't do typechecking in the correct order

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#47]
The equality operator of literals returns true even if only the lexical forms are equal, this means for example that the boolean true
is equal to the string "true".

**Comment by bigerl** [comment]
Thx. That's right. 

I also had a look at the spaceship operator. It also needs updating. 
Related things that need patching are: 
- define a total order for the space ship operator. It must include an ordering between the types that also allows to add more types.
- actually use the bits bits at the NodeBackendHandle->NodeID->LiteralType as a shorthand the xsd datatypes in the space ship and equal operators
- use LiteralType bits in the space ship and equal operators of Literal

**Comment by liss-h** [comment]
#56
