### ISSUE TITLE
Fixed IDs for LiteralDatatypes

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#52]
Literal datatypes should have fixed IDs. This enables faster processing of type hierarchies. datatype <-> ID mapping should must be available at compile time. It would be beneficial if it would neither depend on the DatatypeRegistry nor on the NodeStorage. 

- [x] Every NodeStorage must use these fixed IDs for the IRIs of Datatypes. 
- [x] These IDs should be used in Literal datatype handling instead if the datatype IRI.

**Comment by AtesComp** [comment]
How are user defined datatypes managed if the IDs are expected at compile time?  XSD types are not the only types for literals.  If this is "just" for well known XSD datatypes, then ok.

**Comment by bigerl** [comment]
For now, if a datatype is supposed to support certain operations, like numeric operations, boolean operations or ordering, it must register these operations at compile time. Only such types must define their ID at compile time. All others are gives IDs at runtime as usual.

**Comment by liss-h** [comment]
Development in [feature/fixed-datatype-ids](https://github.com/rdf4cpp/rdf4cpp/tree/feature/fixed-datatype-ids). Currently doesn't compile in CI because the stdlib we are using there does not support constexpr `std::variant` (and/or `std::string`).

**Comment by liss-h** [comment]
fixed by #65
