### ISSUE TITLE
Date Type Implemenation

### ISSUE THREAD

**Issue by bigerl** [TortugaAttack/rdf4cpp#53]
- [x] date
- [x] dateTime
  - [x] dateTimeStamp
- [x] gDay
- [x] gMonth
- [x] gMonthDay
- [x] gYear
- [x] gYearMonth
- [x] time

Should be implemented using ~~https://github.com/HowardHinnant/date~~ `<chrono>` from `libstdc++13`.

**Comment by liss-h** [comment]
Also: 17.4.5 Functions on Dates and Times https://www.w3.org/TR/sparql11-query/#func-date-time

- [x] 17.4.5.1 now
- [x] 17.4.5.2 year
- [x] 17.4.5.3 month
- [x] 17.4.5.4 day
- [x] 17.4.5.5 hours
- [x] 17.4.5.6 minutes
- [x] 17.4.5.7 seconds
- [x] 17.4.5.8 timezone
- [x] 17.4.5.9 tz

**Comment by mcb5637** [comment]
- [ ] date/time arithmetic
  - [x] dateTime - dateTime -> duration
  - [x] dateTime +- duration -> dateTime
  - [x] duration +- duration -> duration
  - [x] duration */ double -> duration
  - [x] duration / duration -> double
- [x] duration
  - [x] yearMonthDuration
  - [x] dayTimeDuration
- [x] promotion (should solve cross compare)
- [x] inlining
  - [x] dateTimeStamp
  - [x] duration
- [x] node storage
  - [x] fully inlined: time, year, month, day, MonthDay
  - [x] done: date, dateTime, dateTimeStamp, yearMonth, duration, dtDuration, ymDuration
- [x] gcc
- [x] CI
- [x] noexcept pass over everything
