### ISSUE TITLE
C-style casts should be replaced

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#60]
C-style casts have a great potential for bugs and undefined behaviour, because
they can perform any kind of c++-style cast to make the conversion work (including reinterpret_cast and const_cast).
In almost all cases you don't actually want to reinterpret memory or strip away const, but a C-style cast will happily do
both and give you no warning it did so.

In my opinion they don't belong in a modern C++ codebase and should all be replaced by the appropriate c++-style casts.
We should also enable `-Wold-style-cast` and `-Wcast-qual`.

Just look at this:
```c++
#include <iostream>
#include <string>

struct S {
    void *ignore; // the allocator occupies this space
    size_t len;

    void some_func() {
        std::cout << "len is: " << len << '\n';
    }
};

int main() {
    std::string const s = "123";
    S &b = (S &)s; // no longer const; and the conversion just doesn't make any sense

    b.some_func();
}
```

Yes, this works gives no warning by default and prints "len is: 3", see: https://godbolt.org/z/oe1nx93aj

**Comment by bigerl** [comment]
Makes sense and I agree. I wasn't aware that the above code snipped would work. It's basically a reinterpret_cast + a const_cast. spooky.

**Comment by liss-h** [comment]
see #62
