### ISSUE TITLE
Add error support to numeric literal ops

### ISSUE THREAD

**Issue by liss-h** [TortugaAttack/rdf4cpp#64]
The (sparql) standard requires to raise "dynamic errors" under certain conditions in numeric operations which is currently not possible.
The problem is that the functions are marked noexcept and the return type does not allow for error value return.

There are two solutions:
1. remove the noexcept specification and just throw exceptions in the appropriate cases
    - trivial to implement
    - possibly bad performance
2. change the return type to be something like `std::expected<op_result_type, op_error>`
    - requires either: a. finding a library implementing something like it; or b. implementing our own until c++23 arrives

A decision needs to be made before merging some parts of the code for #45 (mainly related to one-side-bounded ap integer types, as there is no clear alternative to erroring on bound violation).

**Comment by bigerl** [comment]
good point. a portable option would be https://conan.io/center/expected-lite

Let's discuss the details in our next meeting.
